name: Periodic Health Check

# on:
#   schedule:
#     - cron: '0 * * * *'

jobs:
  health_check_on_earth:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deoloyed service url
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-h8o5.onrender.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false